
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}

server:
  port: 8761

#spring:
#  zipkin:
#    base-url: http://zipkin:9411

management:
  tracing:
    sampling:
      probability: 1.0
