deploy:
  name: Deploy Docker Image
  runs-on: ubuntu-latest
  needs: build

  steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Debug: List target directory
    - name: Debug: List target directory
      run: ls -R target

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t janindu3/discovery-server:${{ github.sha }} .
        docker tag janindu3/discovery-server:${{ github.sha }} janindu3/discovery-server:latest
        docker push janindu3/discovery-server:${{ github.sha }}
        docker push janindu3/discovery-server:latest