name: CI/CD for Local Development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use 'ubuntu-latest' for Linux

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Replace with your Java version

      - name: Install Dependencies
        run: |
          ./gradlew dependencies # For Java projects
          npm install            # For Node.js projects (if applicable)

      - name: Run Tests
        run: ./gradlew test

      - name: Build Docker Image
        run: docker build -t my-service:latest .
        if: success()

      - name: Run Docker Compose (Optional)
        run: docker-compose up -d
